"use client"

import type React from "react"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Users, GraduationCap, DollarSign, CalendarDays, BarChart, Download, Loader2 } from "lucide-react"
import { useToast } from "@/hooks/use-toast" // Assuming useToast is available

interface Report {
  id: string
  title: string
  description: string
  icon: React.ElementType
  type: "student" | "academic" | "financial" | "attendance"
}

const mockReports: Report[] = [
  {
    id: "student-enrollment",
    title: "Student Enrollment Report",
    description: "Detailed list of all enrolled students with their current status.",
    icon: Users,
    type: "student",
  },
  {
    id: "grade-summary",
    title: "Grade Summary Report",
    description: "Overview of average grades across subjects and classes.",
    icon: GraduationCap,
    type: "academic",
  },
  {
    id: "attendance-summary",
    title: "Daily Attendance Summary",
    description: "Consolidated attendance records for a selected date or period.",
    icon: CalendarDays,
    type: "attendance",
  },
  {
    id: "fee-collection",
    title: "Fee Collection Report",
    description: "Summary of collected and outstanding fees.",
    icon: DollarSign,
    type: "financial",
  },
  {
    id: "teacher-performance",
    title: "Teacher Performance Report",
    description: "Analysis of teacher-specific metrics and class performance.",
    icon: BarChart,
    type: "academic",
  },
]

export default function ReportsSection() {
  const [generatingReport, setGeneratingReport] = useState<string | null>(null)
  const { toast } = useToast()

  const handleGenerateReport = async (reportId: string, reportTitle: string) => {
    setGeneratingReport(reportId)
    toast({
      title: `Generating "${reportTitle}"...`,
      description: "This may take a moment.",
    })
    // Simulate API call for report generation
    await new Promise((resolve) => setTimeout(resolve, 2000))
    setGeneratingReport(null)
    toast({
      title: `"${reportTitle}" Generated!`,
      description: "Your report is ready for download.",
      variant: "success",
    })
    // In a real application, you would trigger a download or redirect to a report view
    console.log(`Report "${reportTitle}" generated.`)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports & Analytics</h1>
          <p className="text-gray-600">Generate and view various school reports</p>
        </div>
        <Button className="bg-blue-600 hover:bg-blue-700">
          <Download className="w-4 h-4 mr-2" />
          Export All Data
        </Button>
      </div>

      {/* Report Categories */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {mockReports.map((report) => (
          <Card key={report.id}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-lg font-medium">{report.title}</CardTitle>
              <report.icon className="h-6 w-6 text-gray-500" />
            </CardHeader>
            <CardContent>
              <p className="text-sm text-gray-600 mb-4">{report.description}</p>
              <Button
                className="w-full bg-blue-600 hover:bg-blue-700"
                onClick={() => handleGenerateReport(report.id, report.title)}
                disabled={generatingReport === report.id}
              >
                {generatingReport === report.id ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  "Generate Report"
                )}
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Reports (Placeholder) */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Generated Reports</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div>
                <p className="text-sm font-medium text-gray-800">Student Enrollment Report - 2025-07-18</p>
                <p className="text-xs text-gray-600">Generated by Admin User</p>
              </div>
              <Button variant="ghost" size="sm">
                <Download className="w-4 h-4" />
              </Button>
            </div>
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div>
                <p className="text-sm font-medium text-gray-800">Grade Summary Report - Q2 2025</p>
                <p className="text-xs text-gray-600">Generated by Admin User</p>
              </div>
              <Button variant="ghost" size="sm">
                <Download className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
