-- Connect as SYSTEM or SYS user to create the school management user
-- Run this script as DBA

-- Create tablespace for school management system
CREATE TABLESPACE SCHOOL_DATA
DATAFILE 'school_data.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G;

-- Create user for school management system
CREATE USER SCHOOL_ADMIN IDENTIFIED BY school123
DEFAULT TABLESPACE SCHOOL_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON SCHOOL_DATA;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE, DBA TO SCHOOL_ADMIN;
GRANT CREATE SESSION TO SCHOOL_ADMIN;
GRANT CREATE TABLE TO SCHOOL_ADMIN;
GRANT CREATE SEQUENCE TO SCHOOL_ADMIN;
GRANT CREATE VIEW TO SCHOOL_ADMIN;
GRANT CREATE PROCEDURE TO SCHOOL_ADMIN;
GRANT CREATE TRIGGER TO SCHOOL_ADMIN;

-- Additional privileges for Spring Boot JPA
GRANT SELECT_CATALOG_ROLE TO SCHOOL_ADMIN;
GRANT EXECUTE ON SYS.DBMS_LOCK TO SCHOOL_ADMIN;

COMMIT;
