-- Connect as SCHOOL_ADMIN user
-- Create tables for school management system

-- Users table
CREATE TABLE USERS (
    ID NUMBER(19) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('ADMIN', 'TEACHER', 'STUDENT', 'PARENT')),
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Students table
CREATE TABLE STUDENTS (
    ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) REFERENCES USERS(ID) ON DELETE CASCADE,
    STUDENT_ID VARCHAR2(20) UNIQUE NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(10) CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
    ADDRESS CLOB,
    PHONE VARCHAR2(20),
    PARENT_NAME VARCHAR2(100),
    PARENT_PHONE VARCHAR2(20),
    PARENT_EMAIL VARCHAR2(100),
    ADMISSION_DATE DATE DEFAULT SYSDATE,
    CLASS_ID NUMBER(19),
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Teachers table
CREATE TABLE TEACHERS (
    ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) REFERENCES USERS(ID) ON DELETE CASCADE,
    TEACHER_ID VARCHAR2(20) UNIQUE NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(10) CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
    ADDRESS CLOB,
    PHONE VARCHAR2(20),
    QUALIFICATION VARCHAR2(200),
    EXPERIENCE NUMBER(3),
    SALARY NUMBER(10,2),
    JOIN_DATE DATE DEFAULT SYSDATE,
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Classes table
CREATE TABLE CLASSES (
    ID NUMBER(19) PRIMARY KEY,
    CLASS_NAME VARCHAR2(50) NOT NULL,
    SECTION VARCHAR2(10),
    CLASS_TEACHER_ID NUMBER(19) REFERENCES TEACHERS(ID),
    ACADEMIC_YEAR VARCHAR2(10) NOT NULL,
    CAPACITY NUMBER(3) DEFAULT 30,
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(CLASS_NAME, SECTION, ACADEMIC_YEAR)
);

-- Subjects table
CREATE TABLE SUBJECTS (
    ID NUMBER(19) PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(100) NOT NULL,
    SUBJECT_CODE VARCHAR2(20) UNIQUE NOT NULL,
    DESCRIPTION CLOB,
    CREDITS NUMBER(2) DEFAULT 1,
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Update Students table to add foreign key for class
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENT_CLASS 
FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID);

-- Class-Subject mapping table
CREATE TABLE CLASS_SUBJECTS (
    CLASS_ID NUMBER(19) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    SUBJECT_ID NUMBER(19) REFERENCES SUBJECTS(ID) ON DELETE CASCADE,
    TEACHER_ID NUMBER(19) REFERENCES TEACHERS(ID),
    PRIMARY KEY (CLASS_ID, SUBJECT_ID)
);

-- Marks table
CREATE TABLE MARKS (
    ID NUMBER(19) PRIMARY KEY,
    STUDENT_ID NUMBER(19) REFERENCES STUDENTS(ID) ON DELETE CASCADE,
    SUBJECT_ID NUMBER(19) REFERENCES SUBJECTS(ID) ON DELETE CASCADE,
    CLASS_ID NUMBER(19) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    EXAM_TYPE VARCHAR2(50) NOT NULL,
    MARKS_OBTAINED NUMBER(5,2),
    TOTAL_MARKS NUMBER(5,2) NOT NULL,
    EXAM_DATE DATE NOT NULL,
    ACADEMIC_YEAR VARCHAR2(10) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Attendance table
CREATE TABLE ATTENDANCE (
    ID NUMBER(19) PRIMARY KEY,
    STUDENT_ID NUMBER(19) REFERENCES STUDENTS(ID) ON DELETE CASCADE,
    CLASS_ID NUMBER(19) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    ATTENDANCE_DATE DATE NOT NULL,
    STATUS VARCHAR2(10) NOT NULL CHECK (STATUS IN ('PRESENT', 'ABSENT', 'LATE')),
    REMARKS VARCHAR2(500),
    MARKED_BY NUMBER(19) REFERENCES TEACHERS(ID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(STUDENT_ID, ATTENDANCE_DATE)
);

-- Timetable table
CREATE TABLE TIMETABLE (
    ID NUMBER(19) PRIMARY KEY,
    CLASS_ID NUMBER(19) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    SUBJECT_ID NUMBER(19) REFERENCES SUBJECTS(ID) ON DELETE CASCADE,
    TEACHER_ID NUMBER(19) REFERENCES TEACHERS(ID) ON DELETE CASCADE,
    DAY_OF_WEEK VARCHAR2(10) NOT NULL CHECK (DAY_OF_WEEK IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    START_TIME VARCHAR2(8) NOT NULL,
    END_TIME VARCHAR2(8) NOT NULL,
    ROOM_NUMBER VARCHAR2(20),
    ACADEMIC_YEAR VARCHAR2(10) NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Announcements table
CREATE TABLE ANNOUNCEMENTS (
    ID NUMBER(19) PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    AUTHOR_ID NUMBER(19) REFERENCES USERS(ID) ON DELETE CASCADE,
    TARGET_AUDIENCE VARCHAR2(20) NOT NULL CHECK (TARGET_AUDIENCE IN ('ALL', 'STUDENTS', 'TEACHERS', 'PARENTS')),
    PRIORITY VARCHAR2(10) DEFAULT 'NORMAL' CHECK (PRIORITY IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    ACTIVE NUMBER(1) DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Messages table
CREATE TABLE MESSAGES (
    ID NUMBER(19) PRIMARY KEY,
    SENDER_ID NUMBER(19) REFERENCES USERS(ID) ON DELETE CASCADE,
    RECEIVER_ID NUMBER(19) REFERENCES USERS(ID) ON DELETE CASCADE,
    SUBJECT VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    IS_READ NUMBER(1) DEFAULT 0 CHECK (IS_READ IN (0, 1)),
    SENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    READ_DATE TIMESTAMP
);

COMMIT;
