-- Connect as SCHOOL_ADMIN user
-- Create triggers for auto-incrementing primary keys

-- Users trigger
CREATE OR REPLACE TRIGGER TRG_USERS_ID
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT USER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Students trigger
CREATE OR REPLACE TRIGGER TRG_STUDENTS_ID
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT STUDENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Teachers trigger
CREATE OR REPLACE TRIGGER TRG_TEACHERS_ID
BEFORE INSERT ON TEACHERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT TEACHER_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Classes trigger
CREATE OR REPLACE TRIGGER TRG_CLASSES_ID
BEFORE INSERT ON CLASSES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT CLASS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Subjects trigger
CREATE OR REPLACE TRIGGER TRG_SUBJECTS_ID
BEFORE INSERT ON SUBJECTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SUBJECT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Marks trigger
CREATE OR REPLACE TRIGGER TRG_MARKS_ID
BEFORE INSERT ON MARKS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT MARK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Attendance trigger
CREATE OR REPLACE TRIGGER TRG_ATTENDANCE_ID
BEFORE INSERT ON ATTENDANCE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT ATTENDANCE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Timetable trigger
CREATE OR REPLACE TRIGGER TRG_TIMETABLE_ID
BEFORE INSERT ON TIMETABLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT TIMETABLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Announcements trigger
CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENTS_ID
BEFORE INSERT ON ANNOUNCEMENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT ANNOUNCEMENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Messages trigger
CREATE OR REPLACE TRIGGER TRG_MESSAGES_ID
BEFORE INSERT ON MESSAGES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT MESSAGE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Update triggers for timestamp fields
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATE
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_STUDENTS_UPDATE
BEFORE UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_TEACHERS_UPDATE
BEFORE UPDATE ON TEACHERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLASSES_UPDATE
BEFORE UPDATE ON CLASSES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SUBJECTS_UPDATE
BEFORE UPDATE ON SUBJECTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_MARKS_UPDATE
BEFORE UPDATE ON MARKS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_TIMETABLE_UPDATE
BEFORE UPDATE ON TIMETABLE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ANNOUNCEMENTS_UPDATE
BEFORE UPDATE ON ANNOUNCEMENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_DATE := CURRENT_TIMESTAMP;
END;
/

COMMIT;
